const requestsActionTypes = {
	GET_REQUESTS_START: 'GET_REQUESTS_START',
	GET_REQUESTS_SUCCESS: 'GET_REQUESTS_SUCCESS',
	GET_REQUESTS_FAILURE: 'GET_REQUESTS_FAILURE',
	UPDATE_STATUS_START: 'UPDATE_STATUS_START',
	UPDATE_STATUS_SUCCESS: 'UPDATE_STATUS_SUCCESS',
	UPDATE_STATUS_FAILURE: 'UPDATE_STATUS_FAILURE',
	EDIT_REQUESTS_START: 'EDIT_REQUESTS_START',
	EDIT_REQUESTS_SUCCESS: 'EDIT_REQUESTS_SUCCESS',
	EDIT_REQUESTS_FAILURE: 'EDIT_REQUESTS_FAILURE',
	EMPTY_ERROR: 'EMPTY_ERROR',
	ADD_FILTER: 'ADD_FILTER',
	REMOVE_FILTER: '',
};
export default requestsActionTypes;
