const userActionTypes = {
	LOG_IN_START: 'LOG_IN_START',
	LOG_IN_SUCCESS: 'LOG_IN_SUCCESS',
	LOG_IN_FAILURE: 'LOG_IN_FAILURE',
	EMPTY_ERROR: 'EMPTY_ERROR',
	LOG_OUT_START: 'LOG_OUT_START',
	LOG_OUT_SUCCESS: 'LOG_OUT_SUCCESS',
	LOG_OUT_FAILURE: 'LOG_OUT_FAILURE',
};
export default userActionTypes;
